q script-message pmc-quit

# defaults
f cycle fullscreen
ESC set fullscreen no
SPACE cycle pause
left seek -5
right seek +5
up seek +30
down seek -30
0 add volume 5
9 add volume -5
n playlist-next
p playlist-prev

# subs
v cycle subs-visibility
z add sub-delay -0.1
Z add sub-delay 0.1
j cycle sub
J cycle sub down

