p script-message pmc-prev
q script-message pmc-quit
n script-message pmc-next

# defaults
f cycle fullscreen
ESC set fullscreen no
SPACE cycle pause
left seek -5
right seek +5
up seek +30
down seek -30
0 add volume 5
9 add volume -5

# subs
v cycle subs-visibility
z add sub-delay -0.1
Z add sub-delay 0.1
j cycle sub
J cycle sub down

